name: testing
on:
  push:
    branches:
      - master
    paths-ignore:
      - k8s/*.yaml
  workflow_dispatch:
jobs:
  Fetaching-the-code:
    runs-on: ubuntu-latest
    steps:
      - name: code fetch 
        uses: actions/checkout@v3
  Static-code-analysis:
    runs-on: ubuntu-latest
    needs: Fetaching-the-code
    steps:
      - name: fetch code
        uses: actions/checkout@v3
      - name: sonarqube scanning
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: check Quality Gate result
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  Git-leaks:
    runs-on: ubuntu-latest
    needs: Static-code-analysis
    steps:
      - name: fetch code
        uses: actions/checkout@v3
      - name: gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
