name: testing
on:
  push:
    branches:
      - master
    paths-ignore:
      - k8s/deployment.yaml
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:
jobs:
  tetsing:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "Hi this is test, this is from test branch"
  