name: tag_testing
on:
  workflow_dispatch:

jobs:
  tag_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Get latest release tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching latest GitHub release..."
          latest_release=$(gh release view --json tagName -q '.tagName')
          echo "Latest GitHub release tag: $latest_release"
