name: tag_tetsing
on:
  workflow_dispatch:
jobs:
    tag_testing:
        runs-on: ubuntu-latest 
        steps:
          - name: fetch code
            uses: actions/checkout@v3
          - name: fetch release tag 
            run: echo '${{toJson(github)}}'