name: tag_testing
on:
  workflow_dispatch:

jobs:
  tag_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to fetch tags

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        run: |
          echo "All tags:"
          git tag

          # Get latest tag by commit date
          latest_tag=$(git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags | head -n 1)
          echo "Latest tag: $latest_tag"
