name: testing
on: workflow_dispatch
jobs:
    testing:
        runs-on: ubuntu-latest
        steps: 
            - name: getting data about job
              run: echo "${{github.repository}}:${{github.sha}}"