name: testing
on: workflow_dispatch
jobs:
    testing:
        runs-on: ubuntu-latest
        steps: 
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: getting data about job
              run: echo "${{toJson(github)}}"